---
version: 2
sources:
- name: "prophecy-development.dataset"
  database: "prophecy-development"
  schema: "dataset"
  config:
    enabled: true
  tables:
  - name: "raw_customers"
    columns:
    - name: "id"
      type: "INT64"
    - name: "first_name"
      type: "STRING"
    - name: "last_name"
      type: "STRING"
  - name: "raw_orders"
    columns:
    - name: "id"
      type: "INT64"
    - name: "user_id"
      type: "INT64"
    - name: "order_date"
      type: "DATE"
    - name: "status"
      type: "STRING"
